// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/product_handler.go

// Package mock_handler is a generated GoMock package.
package mocks

import (
	models "avito-pvz/internal/models"
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockProductService) AddProduct(ctx context.Context, productType models.ProductType, pvzID uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, productType, pvzID)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductServiceMockRecorder) AddProduct(ctx, productType, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductService)(nil).AddProduct), ctx, productType, pvzID)
}

// DeleteLastProduct mocks base method.
func (m *MockProductService) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastProduct", ctx, pvzID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastProduct indicates an expected call of DeleteLastProduct.
func (mr *MockProductServiceMockRecorder) DeleteLastProduct(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastProduct", reflect.TypeOf((*MockProductService)(nil).DeleteLastProduct), ctx, pvzID)
}

// MockProductHandler is a mock of ProductHandler interface.
type MockProductHandler struct {
	ctrl     *gomock.Controller
	recorder *MockProductHandlerMockRecorder
}

// MockProductHandlerMockRecorder is the mock recorder for MockProductHandler.
type MockProductHandlerMockRecorder struct {
	mock *MockProductHandler
}

// NewMockProductHandler creates a new mock instance.
func NewMockProductHandler(ctrl *gomock.Controller) *MockProductHandler {
	mock := &MockProductHandler{ctrl: ctrl}
	mock.recorder = &MockProductHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductHandler) EXPECT() *MockProductHandlerMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockProductHandler) AddProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProduct", c)
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductHandlerMockRecorder) AddProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductHandler)(nil).AddProduct), c)
}

// DeleteLastProduct mocks base method.
func (m *MockProductHandler) DeleteLastProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteLastProduct", c)
}

// DeleteLastProduct indicates an expected call of DeleteLastProduct.
func (mr *MockProductHandlerMockRecorder) DeleteLastProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastProduct", reflect.TypeOf((*MockProductHandler)(nil).DeleteLastProduct), c)
}
