// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/pvz_handler.go

// Package mock is a generated GoMock package.
package mocks

import (
	models "avito-pvz/internal/models"
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockPvzService is a mock of PvzService interface.
type MockPvzService struct {
	ctrl     *gomock.Controller
	recorder *MockPvzServiceMockRecorder
}

// MockPvzServiceMockRecorder is the mock recorder for MockPvzService.
type MockPvzServiceMockRecorder struct {
	mock *MockPvzService
}

// NewMockPvzService creates a new mock instance.
func NewMockPvzService(ctrl *gomock.Controller) *MockPvzService {
	mock := &MockPvzService{ctrl: ctrl}
	mock.recorder = &MockPvzServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPvzService) EXPECT() *MockPvzServiceMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPvzService) CreatePvz(ctx context.Context, pvz *models.Pvz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPvzServiceMockRecorder) CreatePvz(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPvzService)(nil).CreatePvz), ctx, pvz)
}

// GetPVZs mocks base method.
func (m *MockPvzService) GetPVZs(ctx context.Context, filter models.PvzFilter) ([]models.PvzWithReceptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZs", ctx, filter)
	ret0, _ := ret[0].([]models.PvzWithReceptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZs indicates an expected call of GetPVZs.
func (mr *MockPvzServiceMockRecorder) GetPVZs(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZs", reflect.TypeOf((*MockPvzService)(nil).GetPVZs), ctx, filter)
}

// MockPvzHandler is a mock of PvzHandler interface.
type MockPvzHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPvzHandlerMockRecorder
}

// MockPvzHandlerMockRecorder is the mock recorder for MockPvzHandler.
type MockPvzHandlerMockRecorder struct {
	mock *MockPvzHandler
}

// NewMockPvzHandler creates a new mock instance.
func NewMockPvzHandler(ctrl *gomock.Controller) *MockPvzHandler {
	mock := &MockPvzHandler{ctrl: ctrl}
	mock.recorder = &MockPvzHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPvzHandler) EXPECT() *MockPvzHandlerMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPvzHandler) CreatePvz(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreatePvz", c)
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPvzHandlerMockRecorder) CreatePvz(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPvzHandler)(nil).CreatePvz), c)
}

// GetPvzs mocks base method.
func (m *MockPvzHandler) GetPvzs(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPvzs", c)
}

// GetPvzs indicates an expected call of GetPvzs.
func (mr *MockPvzHandlerMockRecorder) GetPvzs(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPvzs", reflect.TypeOf((*MockPvzHandler)(nil).GetPvzs), c)
}
