// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/pvz_repository.go

// Package mock is a generated GoMock package.
package mocks

import (
	models "avito-pvz/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPvzRepository is a mock of PvzRepository interface.
type MockPvzRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPvzRepositoryMockRecorder
}

// MockPvzRepositoryMockRecorder is the mock recorder for MockPvzRepository.
type MockPvzRepositoryMockRecorder struct {
	mock *MockPvzRepository
}

// NewMockPvzRepository creates a new mock instance.
func NewMockPvzRepository(ctrl *gomock.Controller) *MockPvzRepository {
	mock := &MockPvzRepository{ctrl: ctrl}
	mock.recorder = &MockPvzRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPvzRepository) EXPECT() *MockPvzRepositoryMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPvzRepository) CreatePvz(ctx context.Context, pvz *models.Pvz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPvzRepositoryMockRecorder) CreatePvz(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPvzRepository)(nil).CreatePvz), ctx, pvz)
}

// GetPVZsWithReceptions mocks base method.
func (m *MockPvzRepository) GetPVZsWithReceptions(ctx context.Context, filter models.PvzFilter) ([]models.PvzWithReceptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZsWithReceptions", ctx, filter)
	ret0, _ := ret[0].([]models.PvzWithReceptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZsWithReceptions indicates an expected call of GetPVZsWithReceptions.
func (mr *MockPvzRepositoryMockRecorder) GetPVZsWithReceptions(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZsWithReceptions", reflect.TypeOf((*MockPvzRepository)(nil).GetPVZsWithReceptions), ctx, filter)
}
