// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/reception_handler.go

// Package mock_handler is a generated GoMock package.
package mocks

import (
	models "avito-pvz/internal/models"
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockReceptionService is a mock of ReceptionService interface.
type MockReceptionService struct {
	ctrl     *gomock.Controller
	recorder *MockReceptionServiceMockRecorder
}

// MockReceptionServiceMockRecorder is the mock recorder for MockReceptionService.
type MockReceptionServiceMockRecorder struct {
	mock *MockReceptionService
}

// NewMockReceptionService creates a new mock instance.
func NewMockReceptionService(ctrl *gomock.Controller) *MockReceptionService {
	mock := &MockReceptionService{ctrl: ctrl}
	mock.recorder = &MockReceptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceptionService) EXPECT() *MockReceptionServiceMockRecorder {
	return m.recorder
}

// CloseActiveReception mocks base method.
func (m *MockReceptionService) CloseActiveReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseActiveReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseActiveReception indicates an expected call of CloseActiveReception.
func (mr *MockReceptionServiceMockRecorder) CloseActiveReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseActiveReception", reflect.TypeOf((*MockReceptionService)(nil).CloseActiveReception), ctx, pvzID)
}

// CreateReception mocks base method.
func (m *MockReceptionService) CreateReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockReceptionServiceMockRecorder) CreateReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockReceptionService)(nil).CreateReception), ctx, pvzID)
}

// MockReceptionHandler is a mock of ReceptionHandler interface.
type MockReceptionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockReceptionHandlerMockRecorder
}

// MockReceptionHandlerMockRecorder is the mock recorder for MockReceptionHandler.
type MockReceptionHandlerMockRecorder struct {
	mock *MockReceptionHandler
}

// NewMockReceptionHandler creates a new mock instance.
func NewMockReceptionHandler(ctrl *gomock.Controller) *MockReceptionHandler {
	mock := &MockReceptionHandler{ctrl: ctrl}
	mock.recorder = &MockReceptionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceptionHandler) EXPECT() *MockReceptionHandlerMockRecorder {
	return m.recorder
}

// CloseActiveReception mocks base method.
func (m *MockReceptionHandler) CloseActiveReception(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseActiveReception", c)
}

// CloseActiveReception indicates an expected call of CloseActiveReception.
func (mr *MockReceptionHandlerMockRecorder) CloseActiveReception(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseActiveReception", reflect.TypeOf((*MockReceptionHandler)(nil).CloseActiveReception), c)
}

// CreateReception mocks base method.
func (m *MockReceptionHandler) CreateReception(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateReception", c)
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockReceptionHandlerMockRecorder) CreateReception(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockReceptionHandler)(nil).CreateReception), c)
}
